/**
 * Guru Medical & Healthcare - Comprehensive Clinical Knowledge Base
 * Tailored for Patient Education, Symptom Guidance, Medicine Details & Safe Dosages.
 * Supports English and Marathi (मराठी) for rural & urban patients.
 */

// ---------------------------------------------------------------------------
// 1. COMPREHENSIVE MEDICINE & DOSAGE REPOSITORY
// ---------------------------------------------------------------------------
export const MEDICINE_DOSAGE_BASE = [
  {
    id: 'paracetamol',
    generic: 'Paracetamol / Acetaminophen (500mg / 650mg)',
    popularBrands: ['Dolo 650', 'Crocin 650', 'Calpol 650', 'P-650', 'Pacimol'],
    category: 'Pain & Fever (Antipyretic & Analgesic)',
    prescriptionRequired: false,
    purposeEn: 'Relieves viral fever, headaches, body aches, toothache, and mild joint pain.',
    purposeMr: 'ताप, डोकेदुखी, अंगदुखी, दातदुखी आणि हलकी सांधेदुखी कमी करण्यासाठी.',
    howItWorksEn: 'Blocks chemical messengers (prostaglandins) in the brain that signal pain and set the body temperature high.',
    howItWorksMr: 'मेंदूतील वेदना आणि ताप वाढवणाऱ्या घटकांना रोखून शरीराचे तापमान नियंत्रित करतो.',
    adultDoseEn: '• **Standard Dose:** 1 tablet (650mg) every 6 to 8 hours as needed.\n• **When to Take:** Always AFTER meals with a full glass of water.\n• **Daily Safe Limit:** Maximum 4 tablets (2600mg) per day. NEVER exceed 4000mg in 24 hours.\n• **Gap Between Doses:** Minimum 4 to 6 hours between two doses.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** आवश्यकतेनुसार दर ६ ते ८ तासांनी १ गोळी (६५० मिग्रॅ).\n• **केव्हा घ्यावी:** नेहमी जेवणानंतर किंवा चहा-नाश्त्यानंतर भरपूर पाण्यासोबत.\n• **कमाल मर्यादा:** २४ तासांत जास्तीत जास्त ३ ते ४ गोळ्या. कधीही प्रमाणाबाहेर घेऊ नये.\n• **दोन डोसमधील अंतर:** किमान ४ ते ६ तास अंतर ठेवावे.',
    pediatricDoseEn: '⚠️ DO NOT give adult 650mg tablets to young children! Use pediatric drops or syrup (10-15 mg per kg body weight per dose) strictly under doctor/pharmacist guidance.',
    pediatricDoseMr: '⚠️ लहान मुलांना मोठ्यांची ६५० मिग्रॅ गोळी देऊ नका! बालकांसाठी वजनानुसार योग्य सिरप (उदा. Calpol किंवा Dolo सिरप) डॉक्टरांच्या सल्ल्याने द्या.',
    precautionsEn: 'Avoid alcohol completely while taking paracetamol. If you have liver or kidney problems, consult doctor before taking.',
    precautionsMr: 'दारूचे सेवन टाळा. यकृत (Liver) किंवा किडनीचा आजार असल्यास डॉक्टरांचा सल्ला घ्या.',
    matchedStoreNames: ['Paracetamol 650mg (Dolo 650)', 'Dolo 650']
  },
  {
    id: 'pantoprazole_domperidone',
    generic: 'Pantoprazole (40mg) + Domperidone (30mg SR)',
    popularBrands: ['Pan-D', 'Pan D', 'PanD', 'Pantocid DSR', 'Pantocid', 'Pan-40', 'Pan 40', 'Pantop-D', 'Junior-Lenz'],
    category: 'Gastro & Acidity (Proton Pump Inhibitor + Prokinetic)',
    prescriptionRequired: true,
    purposeEn: 'Treats severe acidity, acid reflux (GERD), heartburn, gas bloating, and nausea/vomiting caused by indigestion.',
    purposeMr: 'अति ॲसिडिटी, छातीतील जळजळ, गॅसमुळे पोट फुगणे आणि मळमळ/उलटीवर गुणकारी.',
    howItWorksEn: 'Pantoprazole reduces acid production in the stomach, while Domperidone speeds up stomach emptying to prevent acid from rising into the food pipe.',
    howItWorksMr: 'पँटोप्राझोल पोटातील आम्ल (Acid) कमी करतो आणि डोम्पेरिडोन अन्नाची हालचाल सुरळीत करून मळमळ थांबवतो.',
    adultDoseEn: '• **Standard Dose:** 1 capsule once daily.\n• **When to Take:** CRITICAL: Take in the morning on an EMPTY STOMACH, exactly 30 to 45 minutes before breakfast with plain water.\n• **Duration:** Usually 5 to 14 days as advised by physician.\n• **Rule:** Swallow whole; do NOT chew or crush the capsule.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** दररोज सकाळी १ कॅप्सूल.\n• **केव्हा घ्यावी:** अत्यंत महत्त्वाचे: सकाळी उपाशीपोटी (नाश्त्याच्या ३० ते ४५ मिनिटे आधी) पाण्यासोबत.\n• **कालावधी:** डॉक्टरांच्या सल्ल्यानुसार ५ ते १४ दिवस.\n• **नियम:** कॅप्सूल चघळू नका, पाण्यासोबत गिळा.',
    pediatricDoseEn: 'Not recommended for small children unless specifically prescribed in pediatric suspension form by a pediatrician.',
    pediatricDoseMr: 'लहान मुलांसाठी डॉक्टरांच्या विशेष प्रिस्क्रिप्शनशिवाय देऊ नये.',
    precautionsEn: 'Avoid long-term continuous use without checking with a doctor. Avoid spicy, oily food and carbonated drinks.',
    precautionsMr: 'महिने न महिने सलग घेऊ नका. अति तिखट, तेलकट आणि चहा-कॉफीचे प्रमाण कमी ठेवा.',
    matchedStoreNames: ['Pan-D Capsules']
  },
  {
    id: 'azithromycin',
    generic: 'Azithromycin (500mg / 250mg)',
    popularBrands: ['Azee 500', 'Azithral 500', 'Zithrox', 'Aziwok'],
    category: 'Antibiotic (Macrolide)',
    prescriptionRequired: true,
    purposeEn: 'Prescription antibiotic for bacterial infections: throat infection (tonsillitis/pharyngitis), chest & bronchial infections, sinus infection, and skin bacterial lesions.',
    purposeMr: 'बॅक्टेरियल संसर्ग: घशातील इन्फेक्शन (टॉन्सिल्स), छातीतील कफ व संसर्ग, सायनस आणि त्वचेवरील इन्फेक्शनवर डॉक्टरांनी दिलेले अँटिबायोटिक.',
    howItWorksEn: 'Stops bacterial growth by preventing bacteria from synthesizing essential proteins needed for their survival.',
    howItWorksMr: 'जिवाणूंची (बॅक्टेरियाची) वाढ रोखून इन्फेक्शन मुळापासून नष्ट करतो.',
    adultDoseEn: '• **Standard Dose:** 1 tablet (500mg) once daily.\n• **When to Take:** Take at the same time every day, either 1 hour before a meal or 2 hours after a meal.\n• **Course Duration:** STRICTLY 3 to 5 consecutive days as prescribed. DO NOT stop on day 2 just because you feel better! Stopping early causes antibiotic resistance.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** दररोज १ गोळी (५०० मिग्रॅ) एकदाच.\n• **केव्हा घ्यावी:** दररोज एकाच वेळी (जेवणाच्या १ तास आधी किंवा जेवणानंतर २ तासांनी).\n• **कोर्सचा कालावधी:** डॉक्टरांनी सांगितल्याप्रमाणे ३ ते ५ दिवस पूर्ण कोर्स करणे बंधनकारक आहे. बरे वाटले तरी कोर्स अर्धवट सोडू नका!',
    pediatricDoseEn: 'Pediatric Azithromycin oral suspension (100mg/5ml or 200mg/5ml) must be dosed strictly according to the child’s body weight by a doctor.',
    pediatricDoseMr: 'मुलांसाठी वजनानुसार विशेष बालरोग सिरप बालरोगतज्ज्ञांच्या सल्ल्यानेच द्यावे.',
    precautionsEn: 'Does NOT cure common viral flu or normal cold viruses. Use only for confirmed bacterial infections. Inform doctor if you have heart rhythm issues or severe liver disease.',
    precautionsMr: 'हे साध्या सर्दी किंवा व्हायरसवर चालत नाही, केवळ बॅक्टेरियल इन्फेक्शनवर चालते. हृदयाचे आजार असल्यास डॉक्टरांना पूर्वकल्पना द्या.',
    matchedStoreNames: ['Azithromycin 500mg (Azee 500)']
  },
  {
    id: 'augmentin',
    generic: 'Amoxicillin (500mg) + Clavulanic Acid (125mg) = 625mg',
    popularBrands: ['Augmentin 625 Duo', 'Moxikind-CV 625', 'Clavam 625', 'Amoxyclav'],
    category: 'Broad-Spectrum Antibiotic (Penicillin + Beta-Lactamase Inhibitor)',
    prescriptionRequired: true,
    purposeEn: 'Treats severe bacterial infections of the lungs (pneumonia, bronchitis), ear-nose-throat, dental abscesses, urinary tract, and postoperative wounds.',
    purposeMr: 'गंभीर बॅक्टेरियल संसर्ग: फुफ्फुसातील संसर्ग (निमोनिया), दातदुखी/हिरड्यांची पू, कान-नाक-घशाचे संसर्ग, मूत्रमार्गाचे इन्फेक्शन आणि जखमा.',
    howItWorksEn: 'Amoxicillin kills bacteria by destroying their cell wall; Clavulanic acid prevents bacteria from neutralizing amoxicillin.',
    howItWorksMr: 'अमॉक्सिसिलिन जिवाणूंना नष्ट करतो आणि क्लॅव्हुलॅनिक ॲसिड जिवाणूंचा प्रतिकार निष्प्रभ करतो.',
    adultDoseEn: '• **Standard Dose:** 1 tablet (625mg) twice daily (morning & night, 12 hours apart).\n• **When to Take:** Must be taken WITH or immediately after a meal to prevent stomach upset and diarrhea.\n• **Course Duration:** 5 to 7 days. Must complete the entire prescribed course.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** १ गोळी (६२५ मिग्रॅ) दिवसातून दोनदा (सकाळी व रात्री, १२ तासांच्या अंतराने).\n• **केव्हा घ्यावी:** पोट बिघडू नये म्हणून जेवणासोबत किंवा जेवणानंतर लगेच घ्यावी.\n• **कालावधी:** ५ ते ७ दिवस पूर्ण कोर्स करावा.',
    pediatricDoseEn: 'Use pediatric dry syrup (Amoxyclav Duo Dry Syrup) measured with dosage syringe as prescribed by a pediatrician.',
    pediatricDoseMr: 'लहान मुलांसाठी पावडर सिरप (Dry Syrup) डॉक्टरांच्या सांगण्यानुसारच मोजून द्यावे.',
    precautionsEn: 'Do NOT take if you have a penicillin allergy. Mild loose motions may occur; take probiotics (Curd/Lactobacillus) to protect gut bacteria.',
    precautionsMr: 'पेनिसिलिनची ॲलर्जी असल्यास अजिबात घेऊ नका. हलके जुलाब होऊ नयेत म्हणून ताक/दही खाणे फायदेशीर ठरते.',
    matchedStoreNames: ['Augmentin 625 Duo']
  },
  {
    id: 'cetirizine',
    generic: 'Cetirizine Hydrochloride (10mg)',
    popularBrands: ['Cetzine', 'Alerid', 'Okacet', 'Zyrtec', 'Cetcip'],
    category: 'Antihistamine / Cold & Allergy',
    prescriptionRequired: false,
    purposeEn: 'Quick relief from runny nose, sneezing fits, allergic cough, itchy throat, watery eyes, insect bites, skin hives, and itching.',
    purposeMr: 'सर्दी, सतत शिंका येणे, ॲलर्जीमुळे येणारा खोकला, डोळ्यातून पाणी येणे, अंगावर गांधी येणे आणि खाज सुटणे यावर जलद आराम.',
    howItWorksEn: 'Blocks histamine, an allergic chemical released by the body during exposure to pollen, dust, animal hair, or viral colds.',
    howItWorksMr: 'शरीरात ॲलर्जी निर्माण करणाऱ्या हिस्टामाइन द्रव्याला निष्प्रभ करून शिंका व खाज थांबवतो.',
    adultDoseEn: '• **Standard Dose:** 1 tablet (10mg) once daily.\n• **When to Take:** Best taken at BEDTIME (night) because it may cause mild drowsiness.\n• **With or Without Food:** Can be taken with or without food with half a glass of water.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** दिवसातून १ गोळी (१० मिग्रॅ).\n• **केव्हा घ्यावी:** रात्री झोपताना घेणे सर्वोत्तम, कारण यामुळे हलकी गुंगी किंवा झोप येऊ शकते.\n• **पाण्यासोबत:** जेवणानंतर रात्री झोपताना १ गोळी घ्यावी.',
    pediatricDoseEn: 'For children aged 2-6: Cetirizine syrup 2.5ml once daily at night. Ages 6-12: 5ml syrup once daily.',
    pediatricDoseMr: '२ ते ६ वर्षे वयाच्या मुलांसाठी २.५ मिली सिरप रात्री, ६ ते १२ वर्षे मुलांसाठी ५ मिली सिरप रात्री.',
    precautionsEn: 'Avoid driving heavy farm machinery or vehicles if you feel drowsy. Do not consume alcohol with Cetirizine.',
    precautionsMr: 'गोळी घेतल्यानंतर गुंगी येत असल्यास वाहन किंवा शेतीची अवजारे चालवणे टाळावे.',
    matchedStoreNames: ['Cetzine 10mg Tablets']
  },
  {
    id: 'telmisartan',
    generic: 'Telmisartan (40mg / 20mg / 80mg)',
    popularBrands: ['Telma 40', 'Telmikind 40', 'Telvas', 'Telsartan'],
    category: 'Cardiac & Blood Pressure (Angiotensin Receptor Blocker - ARB)',
    prescriptionRequired: true,
    purposeEn: 'Controls high blood pressure (Hypertension), prevents heart attacks, strokes, and protects kidney function in diabetic patients.',
    purposeMr: 'रक्तदाब (High BP) नियंत्रित ठेवण्यासाठी, हृदयविकाराचा झटका व पक्षाघाताचा धोका टाळण्यासाठी आणि किडन्यांचे संरक्षण करण्यासाठी.',
    howItWorksEn: 'Relaxes and widens blood vessels so blood flows more smoothly and the heart pumps without strain.',
    howItWorksMr: 'रक्तवाहिन्या मोकळ्या करून रक्तदाब कमी करतो, ज्यामुळे हृदयावर ताण पडत नाही.',
    adultDoseEn: '• **Standard Dose:** 1 tablet (40mg) once daily.\n• **When to Take:** Take at the exact same fixed time every single morning with water (with or without food).\n• **Golden Rule:** Lifelong maintenance therapy. NEVER stop abruptly without doctor’s instruction, even if your BP reading is normal!',
    adultDoseMr: '• **प्रौढांसाठी डोस:** दररोज सकाळी १ गोळी (४० मिग्रॅ).\n• **केव्हा घ्यावी:** दररोज एकाच निश्चित वेळी (उदा. सकाळी नाश्त्यानंतर) नियमित घ्यावी.\n• **महत्त्वाचा नियम:** बीपी सामान्य आला तरी स्वतःहून गोळी बंद करू नका. औषध नियमित चालू ठेवावे.',
    pediatricDoseEn: 'Strictly for adults. Not intended for children.',
    pediatricDoseMr: 'केवळ प्रौढांसाठी. मुलांसाठी नाही.',
    precautionsEn: 'Do not take during pregnancy. Check BP regularly at Guru Medical counter. Avoid high-salt foods and excess pickles.',
    precautionsMr: 'गरोदरपणात घेऊ नये. आहारात मीठ व लोणचे कमी खा. नियमित बीपी तपासा.',
    matchedStoreNames: ['Telma 40 Tablets']
  },
  {
    id: 'metformin',
    generic: 'Metformin Hydrochloride (500mg / 850mg / 1000mg SR)',
    popularBrands: ['Glycomet 500 SR', 'Glyciphage', 'Cetapin', 'Obimet'],
    category: 'Diabetes Care (Biguanide)',
    prescriptionRequired: true,
    purposeEn: 'First-line medication to lower blood sugar in Type 2 Diabetes; improves insulin sensitivity and prevents diabetes complications.',
    purposeMr: 'टाईप २ मधुमेहात (Sugar/Diabetes) रक्तातील साखर नियंत्रित ठेवण्यासाठी आणि शरीरात इन्सुलिनची कार्यक्षमता वाढवण्यासाठी.',
    howItWorksEn: 'Reduces the amount of glucose produced by the liver and helps cells absorb sugar from the bloodstream.',
    howItWorksMr: 'यकृताद्वारे साखर तयार होण्याचे प्रमाण कमी करतो आणि शरीराला इन्सुलिन वापरण्यास मदत करतो.',
    adultDoseEn: '• **Standard Dose:** 1 tablet (500mg SR) once or twice daily as prescribed.\n• **When to Take:** Always WITH or IMMEDIATELY AFTER your main meals (breakfast/dinner). Taking it with food prevents stomach upset or nausea.\n• **Rule:** Do not crush or chew sustained-release (SR) tablets.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** डॉक्टरांच्या सल्ल्यानुसार ५०० मिग्रॅ १ किंवा २ वेळा.\n• **केव्हा घ्यावी:** नेहमी जेवणासोबत किंवा जेवणानंतर लगेच. उपाशीपोटी घेऊ नका जेणेकरून पोटात मळमळ होणार नाही.\n• **नियम:** गोळी चावू नका, पाण्यासोबत गिळा.',
    pediatricDoseEn: 'Requires dedicated endocrinologist supervision for pediatric diabetes.',
    pediatricDoseMr: 'केवळ डॉक्टरांच्या देखरेखीखाली.',
    precautionsEn: 'Keep meals regular to prevent weakness. Monitor fasting and post-meal sugar every 2-4 weeks. Exercise regularly and limit sweets.',
    precautionsMr: 'वेळेवर जेवण करा. साखर नियमित तपासा. रोज किमान ३० मिनिटे चालण्याचा व्यायाम करा.',
    matchedStoreNames: ['Glycomet 500 SR']
  },
  {
    id: 'volini_gel',
    generic: 'Diclofenac Diethylamine + Methyl Salicylate + Menthol + Linseed Oil',
    popularBrands: ['Volini Gel', 'Moov', 'Omnigel', 'Voveran Emulgel', 'Relispray'],
    category: 'Topical Pain Relief (Analgesic & Counter-Irritant)',
    prescriptionRequired: false,
    purposeEn: 'Fast local relief from knee pain, back pain, neck stiffness, shoulder sprain, joint swelling, and muscle strain from physical labor.',
    purposeMr: 'गुडघेदुखी, कंबरदुखी, पाठदुखी, मानेतील आखडणे, शेतातील कामामुळे येणारे अंगदुखी व लचक यावर त्वरित आराम देणारा मलम.',
    howItWorksEn: 'Diclofenac penetrates deep to relieve inflammation, while Menthol provides a soothing cooling sensation followed by warming blood circulation.',
    howItWorksMr: 'डिक्लोफेनाक त्वचेतून आत जाऊन दाह व सूज कमी करतो, तर मेन्थॉल थंडावा व आराम देतो.',
    adultDoseEn: '• **How to Apply:** Squeeze a fingertip amount (2-4 grams) onto painful area.\n• **Frequency:** Apply gently 3 to 4 times daily.\n• **Application Technique:** Rub lightly until absorbed. DO NOT massage vigorously or rub hard over inflamed joints.',
    adultDoseMr: '• **कसा लावावा:** बोटावर मलम घेऊन दुखऱ्या भागावर हलक्या हाताने लावा.\n• **वारंवारता:** दिवसातून ३ ते ४ वेळा.\n• **पद्धत:** जास्त जोराने चोळू नका, हलक्या हाताने पसरावा. लावल्यानंतर हात स्वच्छ धुवावेत.',
    pediatricDoseEn: 'Safe for children above 12 years. Avoid applying near eyes, nose, or mouth.',
    pediatricDoseMr: '१२ वर्षांवरील मुलांसाठी सुरक्षित. डोळे, तोंड व जखमेवर लावू नका.',
    precautionsEn: 'Do NOT apply on open wounds, broken skin, cuts, or burns. Wash hands thoroughly with soap after application.',
    precautionsMr: 'उघडी जखम, कातडी सोललेला भाग किंवा भाजलेल्या त्वचेवर लावू नये.',
    matchedStoreNames: ['Volini Pain Relief Gel (50g)']
  },
  {
    id: 'electral_ors',
    generic: 'Oral Rehydration Salts (WHO Recommended Formula)',
    popularBrands: ['Electral ORS', 'Walyte', 'Prolyte ORS', 'Enerzal'],
    category: 'Dehydration & Electrolyte Replenisher',
    prescriptionRequired: false,
    purposeEn: 'Prevents and treats life-threatening dehydration and electrolyte loss caused by diarrhea, loose motions, vomiting, heatstroke, or heavy sweating in summer.',
    purposeMr: 'जुलाब, उलटी, उन्हाळा, उष्माघात (Heatstroke) किंवा अतिघामामुळे शरीरातील पाण्याचे प्रमाण कमी झाल्यास तातडीने ऊर्जा व इलेक्ट्रोलाइट्स मिळवण्यासाठी.',
    howItWorksEn: 'Restores the exact physiological ratio of sodium, potassium, chloride, and glucose to re-absorb fluids through the intestinal wall.',
    howItWorksMr: 'शरीरातील क्षार, सोडियम, पोटॅशियम आणि ग्लुकोजची पातळी त्वरित पूर्ववत करतो.',
    adultDoseEn: '• **Preparation (Crucial!):** Dissolve 1 entire packet (21.8g) into EXACTLY 1 LITER of clean boiled & cooled drinking water.\n• **Dosage:** Sip continuously throughout the day. Adults: 1 to 2 liters per day during acute loose motions or vomiting.\n• **Rule:** Discard any mixed solution remaining after 24 hours and prepare fresh.',
    adultDoseMr: '• **बनवण्याची पद्धत (अत्यंत महत्त्वाची):** १ पूर्ण पाकीट बरोबर १ लिटर स्वच्छ उकळून थंड केलेल्या पाण्यात पूर्ण विरघळवा.\n• **डोस:** दिवसभरात घोट-घोट प्या. प्रौढांनी जुलाब किंवा उलटी होत असल्यास दिवसाला १ ते २ लिटर ओआरएस पाणी प्यावे.\n• **नियम:** तयार केलेले पाणी २४ तासांनंतर वापरू नये, शिल्लक राहिल्यास फेकून नवीन बनवावे.',
    pediatricDoseEn: 'Give 50ml to 100ml after every loose stool for infants and young children in small frequent spoonfuls.',
    pediatricDoseMr: 'लहान मुलांना प्रत्येक जुलाबानंतर अर्धा ते एक कप (५०-१०० मिली) चमच्याने हळूहळू पाजावे.',
    precautionsEn: 'Do NOT boil the mixed ORS water after adding powder. Do NOT mix with milk, fruit juices, or tea.',
    precautionsMr: 'पावडर पाण्यात टाकल्यानंतर पाणी पुन्हा उकळू नका. पावडर दूध, चहा किंवा ज्यूसमध्ये टाकू नका, फक्त साध्या पाण्यात टाका.',
    matchedStoreNames: ['Electral ORS Powder (WHO Formula)']
  },
  {
    id: 'shelcal',
    generic: 'Calcium Carbonate (500mg elemental calcium) + Vitamin D3 (250 IU)',
    popularBrands: ['Shelcal 500', 'Cipcal 500', 'Gemcal', 'Calcimax'],
    category: 'Bone Health & Supplements',
    prescriptionRequired: false,
    purposeEn: 'Builds bone density, treats calcium deficiency, osteoporosis, joint pain, muscle weakness, and is essential for menopausal women and post-fracture recovery.',
    purposeMr: 'हाडांची मजबुती, हाडांची झीज (Osteoporosis), गुडघेदुखी, कॅल्शियमची कमतरता आणि फ्रॅक्चरनंतर हाडे जुळण्यासाठी.',
    howItWorksEn: 'Supplies bioavailable calcium to replenish bone matrix, while Vitamin D3 assists the intestines in absorbing calcium into the bloodstream.',
    howItWorksMr: 'हाडांना आवश्यक कॅल्शियम पुरवतो आणि व्हिटॅमिन डी३ आतड्यांमधून कॅल्शियम शोषण्यास मदत करतो.',
    adultDoseEn: '• **Standard Dose:** 1 tablet once daily.\n• **When to Take:** Take AFTER lunch or dinner with a glass of water.\n• **Tip:** Best taken in the afternoon or evening; do not take on an empty stomach.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** दररोज १ गोळी.\n• **केव्हा घ्यावी:** दुपारच्या किंवा रात्रीच्या जेवणानंतर पाण्यासोबत घ्यावी. उपाशीपोटी घेऊ नका.',
    pediatricDoseEn: 'Children should use pediatric calcium syrups (like Shelcal syrup or Kidcal) if diagnosed with deficiency.',
    pediatricDoseMr: 'लहान मुलांसाठी कॅल्शियम सिरप डॉक्टरांच्या सल्ल्याने द्यावे.',
    precautionsEn: 'Patients with kidney stones should consult a physician before prolonged calcium supplementation.',
    precautionsMr: 'किडनी स्टोनचा (मूतखडा) त्रास असलेल्या रुग्णांनी डॉक्टरांचा सल्ला घेऊनच गोळ्या घ्याव्यात.',
    matchedStoreNames: ['Shelcal 500 Calcium & Vitamin D3']
  },
  {
    id: 'ascoril_ls',
    generic: 'Levosalbutamol (1mg) + Ambroxol (30mg) + Guaiphenesin (50mg) / 5ml',
    popularBrands: ['Ascoril LS Syrup', 'Ambrodil LX', 'Bro-Zedex', 'Macbery'],
    category: 'Respiratory & Cough Relief (Bronchodilator + Mucolytic + Expectorant)',
    prescriptionRequired: true,
    purposeEn: 'Clears productive (wet) cough with thick chest phlegm, wheezing, bronchitis, and chest congestion in adults and children.',
    purposeMr: 'छातीत भरलेला घट्ट कफ, छातीत घरघर होणे, छातीत जडपणा आणि ओला खोकला बाहेर काढून मोकळा श्वास घेण्यासाठी.',
    howItWorksEn: 'Ambroxol liquefies thick sticky mucus, Guaiphenesin loosens airway phlegm, and Levosalbutamol opens up bronchial breathing tubes.',
    howItWorksMr: 'अँब्रॉक्सोल घट्ट कफ पातळ करतो, ग्वायफेनेसिन कफ खोकून बाहेर काढतो आणि लेव्होसाल्ब्युटामॉल श्वासनलिका मोकळी करतो.',
    adultDoseEn: '• **Adult Dose:** 10 ml (2 teaspoonfuls) three times daily (TDS).\n• **When to Take:** After meals with a measuring cup.\n• **Supportive Action:** Drink warm water throughout the day to help dissolve phlegm.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** १० मिली (२ चमचे) दिवसातून ३ वेळा.\n• **केव्हा घ्यावे:** जेवणानंतर मोजून घ्यावे. सोबत कोमट पाणी प्यावे जेणेकरून कफ लवकर पातळ होईल.',
    pediatricDoseEn: 'Children 6-12 years: 5 ml twice to three times daily. Children 2-5 years: 2.5 ml three times daily.',
    pediatricDoseMr: '६ ते १२ वर्षे: ५ मिली दिवसातून २-३ वेळा. २ ते ५ वर्षे: २.५ मिली दिवसातून ३ वेळा.',
    precautionsEn: 'May cause mild hand tremors or rapid pulse temporarily. Not recommended for dry tickly throat cough without phlegm.',
    precautionsMr: 'हा सिरप ओल्या कफासाठी आहे, कोरड्या खोकल्यासाठी डेक्सट्रोमेथॉर्फन (Dextromethorphan) सिरप वापरावा.',
    matchedStoreNames: ['Ascoril LS Cough Syrup']
  },
  {
    id: 'betadine_ointment',
    generic: 'Povidone Iodine 5% w/w',
    popularBrands: ['Betadine 5%', 'Cipladine', 'Wokadine', 'Povizol'],
    category: 'First Aid & Antiseptic Ointment',
    prescriptionRequired: false,
    purposeEn: 'Prevents and treats bacterial, fungal, and viral infections in minor cuts, wounds, farm scratches, burns, and surgical stitches.',
    purposeMr: 'कापणे, खरचटणे, शेतातील जखमा, जळणे आणि टाके पडलेल्या जखमांमध्ये पू व जंतूसंसर्ग होऊ नये यासाठी.',
    howItWorksEn: 'Releases iodine slowly to destroy microbial cell walls, killing germs on contact without delaying natural tissue healing.',
    howItWorksMr: 'जंतुनाशक आयोडीन हळूहळू सोडून जखमेवरील सर्व जंतूंचा खात्मा करतो.',
    adultDoseEn: '• **How to Use:** 1. Clean the wound with clean water or sterile saline.\n2. Gently dry with clean gauze.\n3. Apply a thin layer of Betadine ointment.\n4. Cover with sterile dressing or bandage if exposed to farm dust.\n• **Frequency:** Apply 1 to 2 times daily.',
    adultDoseMr: '• **कसे वापरावे:** १. जखम स्वच्छ पाण्याने धुवा.\n२. स्वच्छ सुती कापडाने अलगद कोरडी करा.\n३. बेटाडाइन मलमचा हलका थर लावा.\n४. शेतातील धूळ-माती बसू नये म्हणून पट्टी (Bandage) बांधा.\n• **वारंवारता:** दिवसातून १ ते २ वेळा.',
    pediatricDoseEn: 'Safe for children. Avoid putting inside eyes or mouth.',
    pediatricDoseMr: 'लहान मुलांसाठी सुरक्षित. डोळे किंवा तोंडात जाऊ देऊ नका.',
    precautionsEn: 'Do not use if known allergy to iodine or severe thyroid disease.',
    precautionsMr: 'आयोडीनची ॲलर्जी असल्यास वापरू नका.',
    matchedStoreNames: ['Betadine 5% Antiseptic Ointment']
  },
  {
    id: 'becosules',
    generic: 'Vitamin B-Complex (B1, B2, B3, B6, B12, Folic Acid) + Vitamin C + Zinc',
    popularBrands: ['Becosules Z', 'Cobadex Forte', 'Surbex-T', 'Neurobion Forte'],
    category: 'Vitamins & Supplements',
    prescriptionRequired: false,
    purposeEn: 'Heals painful mouth ulcers, cures tongue blisters, boosts daily energy, aids post-infection recovery, and treats vitamin deficiencies.',
    purposeMr: 'तोंडातील अल्सर (तोंड येणे), जिभेवर फोड येणे, अशक्तपणा, थकवा दूर करण्यासाठी आणि आजारपणानंतर ताकद भरून काढण्यासाठी.',
    howItWorksEn: 'Provides water-soluble vitamins crucial for mucosal repair, nerve conduction, cellular metabolism, and tissue regeneration.',
    howItWorksMr: 'तोंडाच्या आतील नाजूक त्वचेची जलद दुरुस्ती करतो आणि मज्जासंस्थेला व पेशींना ऊर्जा पुरवतो.',
    adultDoseEn: '• **Standard Dose:** 1 capsule once daily.\n• **When to Take:** After breakfast or lunch with plenty of water.\n• **Duration:** 7 to 15 days for mouth ulcers; 1 month for chronic fatigue.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** दररोज १ कॅप्सूल.\n• **केव्हा घ्यावी:** सकाळी नाश्त्यानंतर किंवा दुपारच्या जेवणानंतर भरपूर पाण्यासोबत.\n• **कालावधी:** तोंड आले असल्यास ७ ते १० दिवस; अशक्तपणासाठी १ महिना.',
    pediatricDoseEn: 'For older children (>10 years): 1 capsule daily. Younger children should use B-complex drops/syrup.',
    pediatricDoseMr: '१० वर्षांवरील मुलांसाठी १ कॅप्सूल. लहान मुलांसाठी बी-कॉम्प्लेक्स सिरप द्यावे.',
    precautionsEn: 'Causes bright yellow-colored urine, which is completely harmless (excess riboflavin being excreted).',
    precautionsMr: 'लघवीचा रंग थोडा पिवळा होऊ शकतो, हे अगदी सामान्य आहे, घाबरण्याचे कारण नाही.',
    matchedStoreNames: ['Becosules Z Multivitamin Capsules']
  },
  {
    id: 'cremaffin',
    generic: 'Liquid Paraffin (3.75ml) + Milk of Magnesia (11.25ml) / 15ml',
    popularBrands: ['Cremaffin Plus', 'Dulcolax', 'Looz', 'Softovac'],
    category: 'Laxative / Constipation Relief',
    prescriptionRequired: false,
    purposeEn: 'Relieves acute and chronic constipation, painful hard stools, piles (hemorrhoids), and anal fissures.',
    purposeMr: 'बद्धकोष्ठता (शौचास कडक होणे), पोट साफ न होणे, मूळव्याध (Piles) आणि शौचाच्या जागी होणाऱ्या त्रासावर पोट साफ करणारे औषध.',
    howItWorksEn: 'Milk of Magnesia draws water into the bowel to soften stools, while Liquid Paraffin lubricates the intestinal tract for painless passage.',
    howItWorksMr: 'मॅग्नेशिया शौचास मऊ करतो आणि लिक्विड पॅराफिन आतड्यांना गुळगुळीत करून विनात्रास पोट साफ करतो.',
    adultDoseEn: '• **Adult Dose:** 15ml to 30ml (1 to 2 tablespoonfuls).\n• **When to Take:** At BEDTIME with half a glass of warm water.\n• **Expected Action:** Gentle bowel movement occurs within 6 to 8 hours next morning.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** १५ ते ३० मिली (१ ते २ मोठे चमचे).\n• **केव्हा घ्यावे:** रात्री झोपताना अर्धा ग्लास कोमट पाण्यासोबत.\n• **परिणाम:** दुसऱ्या दिवशी सकाळी पोट व्यवस्थित साफ होते.',
    pediatricDoseEn: 'Children 5-12 years: 5ml to 10ml at bedtime only as recommended by a doctor.',
    pediatricDoseMr: '५ ते १२ वर्षे: ५ ते १० मिली फक्त डॉक्टरांच्या सल्ल्याने.',
    precautionsEn: 'Do not use continuously for weeks without addressing dietary fiber and water intake. Drink 2.5 to 3 liters of water daily.',
    precautionsMr: 'आहारात हिरव्या पालेभाज्या, फळे आणि पाण्याचे प्रमाण वाढवा.',
    matchedStoreNames: ['Cremaffin Plus Emulsion']
  },
  {
    id: 'liv52',
    generic: 'Himsra (Caper Bush) + Kasani (Chicory) Ayurvedic Formulation',
    popularBrands: ['Liv.52 DS', 'Liv.52 Syrup', 'Lupin Hepashine'],
    category: 'Ayurvedic Liver Tonic',
    prescriptionRequired: false,
    purposeEn: 'Supports liver health, treats loss of appetite, fatty liver, jaundice recovery, sluggish liver, and counteracts chemical toxins.',
    purposeMr: 'यकृताचे (Liver) आरोग्य, भूक मंदावणे, फॅटी लिव्हर, काविळीनंतर यकृत मजबूत करणे आणि पचनशक्ती वाढवण्यासाठी.',
    howItWorksEn: 'Protects liver cells against lipid peroxidation and accelerates recovery of hepatocyte functioning.',
    howItWorksMr: 'यकृताच्या पेशींचे संरक्षण करून भूक वाढवतो व पचन सुधारतो.',
    adultDoseEn: '• **Adult Dose:** 1 to 2 tablets twice daily.\n• **When to Take:** 30 minutes before food with warm water.\n• **Duration:** 1 to 3 months.',
    adultDoseMr: '• **प्रौढांसाठी डोस:** १ ते २ गोळ्या दिवसातून २ वेळा.\n• **केव्हा घ्याव्यात:** जेवणाच्या ३० मिनिटे आधी कोमट पाण्यासोबत.\n• **कालावधी:** १ ते ३ महिने.',
    pediatricDoseEn: 'Liv.52 syrup: 1 teaspoon (5ml) twice daily before food for children.',
    pediatricDoseMr: 'लहान मुलांसाठी: लिव्ह ५२ सिरप १ चमचा (५ मिली) दिवसातून दोनदा.',
    precautionsEn: 'Ayurvedic formulation with no known side effects when taken at recommended doses.',
    precautionsMr: 'सुरक्षित आयुर्वेदिक औषध.',
    matchedStoreNames: ['Liv.52 DS Tablets (Double Strength)']
  }
];

// ---------------------------------------------------------------------------
// 2. COMPREHENSIVE SICKNESS & DISEASE CLINICAL KNOWLEDGE BASE
// ---------------------------------------------------------------------------
export const SICKNESS_KNOWLEDGE_BASE = [
  {
    id: 'fever_viral',
    keywords: ['fever', 'temperature', 'pyrexia', 'viral fever', 'chills', 'ताप', 'अंग गरम', 'हुडहुडी', 'थंडी'],
    nameEn: 'Viral Fever & General Pyrexia',
    nameMr: 'व्हायरल ताप आणि अंगदुखी',
    explanationEn: 'Fever is your body’s natural defense response. When immune white blood cells detect viruses or bacteria, the brain’s hypothalamus raises your core temperature above 98.6°F (37°C) to kill the invading germs.',
    explanationMr: 'ताप म्हणजे शरीराची रोगप्रतिकारक शक्ती व्हायरस किंवा जंतूंसोबत लढत असल्याचे लक्षण आहे. मेंदू शरीराचे तापमान ९८.६°F पेक्षा जास्त वाढवून जंतूंचा खात्मा करतो.',
    commonCausesEn: 'Seasonal viral infection, influenza, weather transition, common cold, mosquito bites, or exhaustion.',
    commonCausesMr: 'ऋतू बदल, व्हायरल इन्फेक्शन, सर्दी, फ्लू, डास चावणे किंवा अती थकवा.',
    symptomsEn: 'High body temperature (>99°F), shivering, sweating, headache, eye ache, generalized body pain, weakness, and loss of appetite.',
    symptomsMr: 'अंग गरम होणे, थंडी वाजणे, डोकेदुखी, डोळे जळजळणे, अंगदुखी, अशक्तपणा आणि भूक मंदावणे.',
    dosageGuideEn: '• **Immediate Antipyretic:** **Paracetamol 650mg (Dolo 650)**.\n• **Adult Dose:** 1 tablet after food, repeatable every 6 hours if temperature exceeds 100°F (Max 4 tablets in 24 hours).\n• **Child Dose:** Calpol / Paracetamol syrup calculated at 15mg/kg per dose. (NEVER give adult 650mg tablet to young kids).\n• **Hydration:** Drink at least 2.5 liters of fluids (boiled-cooled water, ORS, lemon water).',
    dosageGuideMr: '• **तापावर त्वरित औषध:** **Paracetamol 650mg (Dolo 650)**.\n• **प्रौढांसाठी डोस:** जेवणानंतर १ गोळी. ताप १००°F च्या वर राहिल्यास ६ तासांनंतर पुन्हा घेऊ शकता (दिवसाला जास्तीत जास्त ३ ते ४ गोळ्या).\n• **मुलांसाठी डोस:** बालकांसाठी Calpol सिरप वजनानुसार डॉक्टरांच्या सल्ल्याने द्या.\n• **पाणी व आराम:** दिवसभरात किमान २.५ ते ३ लिटर पाणी/ओआरएस प्या व पूर्ण विश्रांती घ्या.',
    homeCareEn: '• Place a clean cloth soaked in normal tap water on forehead (cold sponge, do not use ice water).\n• Wear loose, light cotton clothing.\n• Eat light khichdi, moong dal soup, apples, and stay hydrated.',
    homeCareMr: '• कपाळावर साध्या पाण्याच्या पट्ट्या ठेवा (बर्फाचे पाणी वापरू नका).\n• सैल, सुती कपडे घाला.\n• हलकी मूगडाळ खिचडी, सूप, फळे खा आणि भरपूर आराम करा.',
    redFlagsEn: '🚨 Rush to hospital if: Fever > 103°F, fever lasting > 3 days, extreme lethargy/unconsciousness, severe vomiting, or red skin rashes (suspected Dengue).',
    redFlagsMr: '🚨 त्वरित हॉस्पिटलमध्ये जा जर: ताप १०३°F पेक्षा जास्त असेल, ताप ३ दिवसांपेक्षा जास्त टिकून राहिला असेल, बेशुद्ध पडणे किंवा अंगावर लाल चट्टे उठत असतील (डेंग्यूची शक्यता).',
    matchedMeds: ['Paracetamol 650mg (Dolo 650)', 'Electral ORS Powder (WHO Formula)']
  },
  {
    id: 'dengue_malaria_typhoid',
    keywords: ['dengue', 'malaria', 'typhoid', 'mosquito fever', 'platelet', 'डेंग्यू', 'मलेरिया', 'टायफॉईड', 'प्लेटलेट'],
    nameEn: 'Mosquito & Water-Borne Fevers (Dengue, Malaria, Typhoid)',
    nameMr: 'डासांमुळे व अस्वच्छ पाण्यामुळे होणारे ताप (डेंग्यू, मलेरिया, टायफॉईड)',
    explanationEn: '• **Dengue:** Transmitted by daytime Aedes mosquitoes. Characterized by high fever, severe eye-socket pain, and drop in blood platelets.\n• **Malaria:** Caused by Plasmodium parasites via nighttime Anopheles mosquitoes. Characterized by shivering fever spikes every 48 hours.\n• **Typhoid:** Caused by Salmonella typhi bacteria via contaminated water/food. Characterized by step-ladder continuous fever, stomach pain, and severe fatigue.',
    explanationMr: '• **डेंग्यू:** एडिस डासामुळे होतो. डोळ्यांच्या मागे तीव्र वेदना, सांधेदुखी आणि प्लेटलेट्स कमी होतात.\n• **मलेरिया:** ॲनॉफिलीस डासामुळे होतो. थंडी वाजून हुडहुडी भरणे आणि ताप येणे.\n• **टायफॉईड:** दूषित पाणी किंवा अन्नामुळे होणारा बॅक्टेरियल ताप. सलग ताप, पोटदुखी व कमालीचा अशक्तपणा.',
    dosageGuideEn: '• **For Dengue:** ONLY Paracetamol 650mg for fever. ⚠️ NEVER take Brufen, Combiflam, Aspirin or Diclofenac as they increase internal bleeding risk! Drink ORS and coconut water continuously.\n• **For Malaria:** Prescription antimalarials (Artemether-Lumefantrine or Chloroquine) only after blood smear test.\n• **For Typhoid:** Prescription antibiotics (Cefixime / Azithromycin) prescribed by a doctor after Widal/Blood Culture test.',
    dosageGuideMr: '• **डेंग्यूसाठी:** केवळ **Paracetamol (Dolo 650)** घ्यावे. ⚠️ ब्रुफेन, कॉम्बीफ्लॅम किंवा इतर पेनकिलर चुकूनही घेऊ नका, कारण त्यामुळे रक्तस्राव होऊ शकतो! नारळ पाणी व ओआरएस सतत प्या.\n• **मलेरियासाठी:** रक्ताची तपासणी करून डॉक्टरांच्या सल्ल्याने मलेरियाच्या गोळ्या घ्या.\n• **टायफॉईडसाठी:** विडाल टेस्ट करून डॉक्टरांच्या प्रिस्क्रिप्शननुसार अँटिबायोटिक्स पूर्ण कोर्स घ्या.',
    homeCareEn: 'Boil drinking water for 10 minutes. Use mosquito nets. Consume papaya leaf extract / kiwi for platelet support, fresh pomegranate juice, and ORS.',
    homeCareMr: 'पिण्याचे पाणी उकळून प्या. घरात डास प्रतिबंधक जाळ्या वापरा. पपईच्या पानांचा रस, किवी, डाळिंब व ओआरएसचे पाणी प्या.',
    redFlagsEn: '🚨 Bleeding from gums/nose, black stools, continuous vomiting, extreme abdominal pain -> IMMEDIATE HOSPITAL ADMISSION REQUIRED.',
    redFlagsMr: '🚨 हिरड्यांतून किंवा नाकातून रक्त येणे, काळी संडास होणे, उलट्या न थांबणे -> तातडीने हॉस्पिटलमध्ये भरती व्हा.',
    matchedMeds: ['Paracetamol 650mg (Dolo 650)', 'Electral ORS Powder (WHO Formula)', 'Azithromycin 500mg (Azee 500)']
  },
  {
    id: 'common_cold_cough',
    keywords: ['cold', 'cough', 'runny nose', 'sore throat', 'sneezing', 'phlegm', 'dry cough', 'wet cough', 'सर्दी', 'खोकला', 'शिंका', 'घसा', 'कफ'],
    nameEn: 'Common Cold, Allergic Rhinitis & Cough',
    nameMr: 'सर्दी, शिंका, खोकला आणि घशाचे इन्फेक्शन',
    explanationEn: 'Upper respiratory viral infections inflame nasal passages and the bronchial tree, causing excessive mucus production, coughing reflexes to expel irritants, and sore throat.',
    explanationMr: 'व्हायरस किंवा धुळीच्या ॲलर्जीमुळे नाकातील व घशातील नसा सुजतात, ज्यामुळे सतत शिंका, नाक गळणे, घशात खवखव आणि खोकला सुरू होतो.',
    dosageGuideEn: '• **For Runny Nose & Sneezing:** **Cetirizine 10mg (Cetzine)** - 1 tablet at night.\n• **For Wet Cough with Phlegm:** **Ascoril LS Syrup** (10ml three times daily after food).\n• **For Dry Irritating Cough:** Dextromethorphan syrup (10ml twice daily).\n• **For Sore Throat:** Warm salt-water gargles 3 times a day + Strepsils lozenges.\n• **For Fever & Headache:** Paracetamol 650mg (1 tablet after meals).',
    dosageGuideMr: '• **शिंका व वाहत्या नाकासाठी:** **Cetzine 10mg** - रात्री झोपताना १ गोळी.\n• **छातीतील ओल्या कफासाठी:** **Ascoril LS Syrup** - १० मिली दिवसातून ३ वेळा जेवणानंतर.\n• **कोरड्या खोकल्यासाठी:** कोरड्या खोकल्याचा सिरप (उदा. Dextromethorphan).\n• **घसा खवखवणे:** कोमट पाण्यात मीठ टाकून गुळण्या करा.\n• **डोकेदुखी व ताप असल्यास:** Dolo 650 गोळी जेवणानंतर.',
    homeCareEn: '• Steam inhalation twice daily with a drop of Eucalyptus/Karvol Plus.\n• Drink warm water with honey, ginger, and turmeric.\n• Avoid chilled water, ice-cream, cold drinks, and dust exposure.',
    homeCareMr: '• दिवसातून दोनदा कोमट पाण्याची वाफ (Steam) घ्या.\n• आल्याचा काढा, हळदीचे दूध किंवा मध-तुळशीचा रस घ्या.\n• थंड पाणी, शीतपेये आणि धूळ पूर्णपणे टाळा.',
    redFlagsEn: '🚨 Wheezing, severe shortness of breath, coughing up blood, or cough persisting over 2 weeks (requires Tuberculosis/Chest X-ray evaluation).',
    redFlagsMr: '🚨 श्वास घेताना शिटीसारखा आवाज येणे, दम लागणे, थुंकीतून रक्त पडणे किंवा खोकला २ आठवड्यांपेक्षा जास्त टिकल्यास छातीचा एक्स-रे करा.',
    matchedMeds: ['Cetzine 10mg Tablets', 'Ascoril LS Cough Syrup', 'Paracetamol 650mg (Dolo 650)']
  },
  {
    id: 'acidity_gerd_gastritis',
    keywords: ['acidity', 'gas', 'heartburn', 'gerd', 'gastric', 'reflux', 'chest burn', 'sour burps', 'ॲसिडिटी', 'गॅस', 'जळजळ', 'करपट ढेकर', 'पित्त'],
    nameEn: 'Acidity, Acid Reflux (GERD) & Gas Bloating',
    nameMr: 'ॲसिडिटी, पित्त, छातीत जळजळ आणि पोटात गॅस होणे',
    explanationEn: 'Occurs when the stomach produces excess hydrochloric acid, or when the lower esophageal sphincter relaxes, letting burning stomach acid splash back up into the food pipe.',
    explanationMr: 'जेव्हा पोटात अतिप्रमाणात ॲसिड (पित्त) तयार होते किंवा अन्ननलिकेचे तोंड सैल पडून ते छातीकडे वर येते, तेव्हा छातीत असह्य जळजळ आणि पोटात गॅस होतो.',
    dosageGuideEn: '• **First-Line Solution:** **Pan-D Capsules** (Pantoprazole + Domperidone).\n• **Exact Timing:** 1 capsule in the morning on an EMPTY STOMACH (30-45 minutes before breakfast).\n• **Instant Liquid Relief:** Antacid syrup (Gelusil / Digene) - 2 teaspoonfuls after meals when acute burning strikes.\n• **Course:** Take Pan-D daily for 5 to 7 days to heal stomach lining irritation.',
    dosageGuideMr: '• **खात्रीशीर औषध:** **Pan-D Capsules** (Pantoprazole + Domperidone).\n• **घेण्याची अचूक वेळ:** दररोज सकाळी उपाशीपोटी (नाश्त्याच्या ३०-४५ मिनिटे आधी) १ कॅप्सूल.\n• **तातडीच्या जळजळीवर:** जेलुसिल किंवा डायजीन सिरप (२ चमचे जेवणानंतर).\n• **कालावधी:** ५ ते ७ दिवस नियमित घ्यावे जेणेकरून पोटातील अल्सरची जळजळ शांत होईल.',
    homeCareEn: '• Have early dinners (at least 2 hours before lying down).\n• Elevate the head of your bed by 6 inches.\n• Drink cold milk or coconut water for rapid soothing.\n• Avoid deeply fried foods, oily snacks, excess chillies, smoking, and continuous tea.',
    homeCareMr: '• जेवल्यानंतर लगेच झोपू नका; किमान २ तास जागे राहा.\n• थंड दूध किंवा शहाळ्याचे पाणी प्या, यामुळे जळजळ लगेच थांबते.\n• चहा, कॉफी, अति तिखट-मसालेदार अन्न आणि तंबाखू टाळा.',
    redFlagsEn: '🚨 Severe central chest pain radiating to left shoulder/jaw with sweating (may be Heart Attack, not acidity!), vomiting dark blood, or black stools.',
    redFlagsMr: '🚨 डाव्या हातात किंवा जबड्यात कळ जाणवणारी छातीत वेदना, सोबत घाम येणे (हा हार्ट अटॅक असू शकतो!), रक्ताची उलटी किंवा काळी संडास होणे.',
    matchedMeds: ['Pan-D Capsules', 'Cremaffin Plus Emulsion']
  },
  {
    id: 'diarrhea_vomiting_foodpoisoning',
    keywords: ['diarrhea', 'loose motion', 'vomiting', 'food poisoning', 'stomach infection', 'vomit', 'जुलाब', 'उलटी', 'अतिसार', 'संडास', 'विषबाधा'],
    nameEn: 'Diarrhea, Loose Motions & Food Poisoning',
    nameMr: 'जुलाब, उलटी, अन्नविषबाधा (Food Poisoning) व डिहायड्रेशन',
    explanationEn: 'Gastroenteritis causes intestinal lining inflammation due to contaminated food/water (E. coli, rotavirus). The gut flushes out water and vital salts, making severe dehydration the primary health risk.',
    explanationMr: 'बाहेरील उघड्या किंवा दूषित अन्न-पाण्यामुळे आतड्यांना जंतुसंसर्ग होतो. शरीर हे जंतू बाहेर टाकण्याच्या प्रयत्नात भरपूर पाणी व जीवनरक्षक क्षार गमावून बसते.',
    dosageGuideEn: '• **CRITICAL PRIORITY #1: Rehydration:** **Electral ORS** - Dissolve 1 sachet in 1 liter clean drinking water; drink 1 glass after every loose motion.\n• **For Stopping Vomiting:** Ondansetron 4mg (Emeset / Ondem) - 1 tablet 30 minutes before food.\n• **For Bacterial Diarrhea (foul smelling/fever):** Ofloxacin + Ornidazole (O2) - 1 tablet twice daily for 3-5 days under doctor prescription.\n• **Gut Flora Restoration:** Probiotic capsules (Econorm / Darolac) twice daily.',
    dosageGuideMr: '• **क्रमांक १ चे जीवनरक्षक औषध:** **Electral ORS** - १ पाकीट १ लिटर स्वच्छ पाण्यात मिसळा; प्रत्येक संडासनंतर १ ग्लास पाणी प्या.\n• **उलटी थांबवण्यासाठी:** Ondansetron 4mg (Emeset/Ondem) - जेवणाच्या किंवा खाण्याच्या ३० मिनिटे आधी १ गोळी.\n• **जिवाणूंच्या संसर्गावर:** ओफ्लॉक्सिन-ऑर्निडाझोल (O2) डॉक्टरांच्या सल्ल्याने दिवसातून २ वेळा.\n• **पोटातील बॅक्टेरियासाठी:** प्रोबायोटिक्स (दही/ताक/इकोनॉर्म) घ्या.',
    homeCareEn: '• Eat the "BRAT" diet: Bananas, Rice khichdi, Applesauce, Toast, plus buttermilk with roasted cumin.\n• Sip ORS water slowly in small mouthfuls; do not gulp large volumes at once if nauseous.',
    homeCareMr: '• मऊ तांदळाची खिचडी, केळी, ताजे ताक आणि डाळिंबाचा रस घ्या.\n• एकाच वेळी जास्त पाणी न पिता थोडे-थोडे घोट-घोट ओआरएसचे पाणी प्या.',
    redFlagsEn: '🚨 Sunken eyes, no urine for >8 hours, high fever, severe stomach cramping, or blood in stools -> RUSH TO HOSPITAL IMMEDIATELY.',
    redFlagsMr: '🚨 डोळे खोल जाणे, ८ तासांपेक्षा जास्त लघवी न होणे, संडासमध्ये रक्त येणे, किंवा चक्कर येऊन पडणे -> त्वरित हॉस्पिटलमध्ये ॲडमिट व्हा.',
    matchedMeds: ['Electral ORS Powder (WHO Formula)', 'Pan-D Capsules']
  },
  {
    id: 'constipation_piles',
    keywords: ['constipation', 'piles', 'hemorrhoids', 'hard stool', 'fissure', 'बद्धकोष्ठता', 'शौचास कडक', 'मूळव्याध', 'फिशर', 'पोट साफ न होणे'],
    nameEn: 'Constipation, Hard Stools & Piles (Hemorrhoids)',
    nameMr: 'बद्धकोष्ठता, शौचास त्रास आणि मूळव्याध (Piles)',
    explanationEn: 'Occurs when colon absorbs too much water due to slow stool transit, lack of fiber, or inadequate fluid intake, leading to hard, dry stools that cause swollen veins (piles) or painful tears (fissures).',
    explanationMr: 'आहारात फायबर (चोथा) आणि पाण्याची कमतरता असल्यामुळे शौच कोरडे व कडक होते. कुंथल्यामुळे गुदद्वाराच्या नसा सुजतात (मूळव्याध) किंवा जखम होते (फिशर).',
    dosageGuideEn: '• **Stool Softener:** **Cremaffin Plus** - 15ml to 25ml at bedtime with warm water.\n• **Bulk-forming Fiber:** Isabgol (Psyllium Husk) - 2 spoonfuls in warm water or milk at bedtime.\n• **Piles Pain / Bleeding:** Piles ointment (Anovate / Shield) with applicator twice daily, plus Daflon 500mg if prescribed by doctor.',
    dosageGuideMr: '• **शौच मऊ होण्यासाठी:** **Cremaffin Plus** - रात्री झोपताना १५ ते २५ मिली कोमट पाण्यासोबत.\n• **पोट साफ करण्यासाठी:** इसबगोल पावडर २ चमचे कोमट पाण्यात रात्री.\n• **मूळव्याधीच्या दुखण्यावर:** डॉक्टरांच्या सल्ल्याने मलम (Anovate Ointment) शौचाच्या जागी लावावा.',
    homeCareEn: '• Drink 3 liters of water daily.\n• Eat fibrous vegetables (leafy greens, carrots, cucumbers, oats, figs, papaya).\n• Take a warm water Sitz bath (sit in a tub of warm water for 15 minutes twice daily to soothe piles pain).',
    homeCareMr: '• दररोज किमान ३ लिटर पाणी प्या.\n• आहारात पपई, पेरू, हिरव्या पालेभाज्या, मोड आलेली कडधान्ये खा.\n• कोमट पाण्याच्या टबमध्ये १०-१५ मिनिटे बसा (Sitz Bath), यामुळे मूळव्याधीच्या सुजेला लगेच आराम मिळतो.',
    redFlagsEn: '🚨 Heavy bright red blood dripping into toilet, extreme throbbing anal pain (thrombosed pile), or unexplained weight loss.',
    redFlagsMr: '🚨 भरपूर रक्त वाहणे किंवा असह्य वेदना होत असल्यास तात्काळ सर्जन किंवा डॉक्टरांना दाखवा.',
    matchedMeds: ['Cremaffin Plus Emulsion']
  },
  {
    id: 'hypertension_bp',
    keywords: ['blood pressure', 'hypertension', 'high bp', 'low bp', 'bp', 'रक्तदाब', 'हाय बीपी', 'लो बीपी', 'चक्कर'],
    nameEn: 'Hypertension (High Blood Pressure) & Low BP',
    nameMr: 'हाय ब्लड प्रेशर (रक्तदाब) आणि लो बीपीचे व्यवस्थापन',
    explanationEn: '• **Normal BP:** 120/80 mmHg.\n• **High BP (Hypertension):** Persistent reading >140/90 mmHg. It is a "silent killer" because it damages arteries, heart, brain, and kidneys without obvious pain.\n• **Low BP (Hypotension):** Below 90/60 mmHg, causing lightheadedness, weakness, and fainting.',
    explanationMr: '• **सामान्य बीपी:** १२०/८० mmHg.\n• **हाय बीपी:** १४०/९० च्या वर सतत राहणे. हा शांत शत्रू आहे कारण कोणतीही पूर्वसूचना न देता हृदय, मेंदू व किडन्यांवर गंभीर परिणाम करतो.\n• **लो बीपी:** ९०/६० च्या खाली जाणे, ज्यामुळे चक्कर येणे व डोळ्यांसमोर अंधारी येते.',
    dosageGuideEn: '• **For High BP:** **Telmisartan 40mg (Telma 40)** or Amlodipine 5mg.\n• **Adult Dose:** 1 tablet once daily every morning without fail.\n• **Strict Rule:** NEVER skip a dose just because you feel fine! BP medicines keep your blood vessels protected daily.\n• **For Low BP:** Electrolyte fluids (Electral ORS), salted lemon water, and rest with feet elevated.',
    dosageGuideMr: '• **हाय बीपीसाठी:** **Telma 40 Tablets** (Telmisartan 40mg) डॉक्टरांच्या सल्ल्यानुसार.\n• **डोस:** दररोज सकाळी १ गोळी नियमित एकाच वेळी घ्यावी.\n• **महत्त्वाचा नियम:** बरे वाटत असले तरी गोळी कधीही बंद करू नका! रोज नियमित गोळी घेणे हेच हृदय सुरक्षित ठेवते.\n• **लो बीपीसाठी:** लिंबू-पाण्यात थोडे मीठ टाकून प्या किंवा ओआरएस प्या आणि पाय उंचावर ठेवून झोपा.',
    homeCareEn: '• Cut salt intake strictly to under 1 teaspoon (5g) per day. Avoid pickles, papads, and salted farsan.\n• Walk briskly for 30 minutes every morning.\n• Monitor BP weekly (Complimentary free checkup available at Guru Medical counter).',
    homeCareMr: '• जेवणात मिठाचे प्रमाण कमी करा. लोणचे, पापड, खारवलेले पदार्थ बंद करा.\n• रोज सकाळी किमान ३० मिनिटे वेगाने चाला.\n• गुरु मेडिकल काउंटरवर येऊन नियमित मोफत डिजिटल बीपी तपासून घ्या.',
    redFlagsEn: '🚨 BP > 180/120 mmHg, sudden blinding headache, blurred vision, chest tightness, or slurred speech (Emergency Stroke/Heart risk -> CALL 108 / 8237729148).',
    redFlagsMr: '🚨 बीपी १८०/१२० पेक्षा जास्त, डोळ्यांसमोर अंधारी, छातीत दुखणे, किंवा बोलताना जीभ अडखळणे (पक्षाघाताचा धोका -> त्वरित १०८ वर फोन करा).',
    matchedMeds: ['Telma 40 Tablets', 'Electral ORS Powder (WHO Formula)']
  },
  {
    id: 'diabetes_sugar',
    keywords: ['diabetes', 'sugar', 'glucose', 'diabetic', 'मधुमेह', 'साखर', 'डायबेटिस', 'इन्सुलिन'],
    nameEn: 'Type 2 Diabetes Mellitus (Blood Sugar Management)',
    nameMr: 'टाईप २ मधुमेह (रक्तातील साखरेचे व्यवस्थापन)',
    explanationEn: 'Occurs when the pancreas does not produce enough insulin or the body’s cells resist insulin. Glucose builds up in the blood, eventually harming nerves, eyes, kidneys, and blood circulation.',
    explanationMr: 'जेव्हा शरीरातील स्वादुपिंड पुरेसे इन्सुलिन तयार करत नाही किंवा पेशी इन्सुलिनला प्रतिसाद देत नाहीत, तेव्हा रक्तातील साखरेचे प्रमाण वाढून मधुमेह होतो.',
    dosageGuideEn: '• **First-Line Medication:** **Metformin 500mg SR (Glycomet 500 SR)**.\n• **Dose:** 1 tablet once or twice daily with or immediately after meals (breakfast/dinner).\n• **Why with meals:** Prevents nausea and stomach upset.\n• **For advanced control:** Glimepiride (1mg/2mg) or Teneligliptin (20mg) strictly as prescribed by your doctor.\n• **Fasting Target:** 80 - 120 mg/dL. **Post-Meal Target:** < 160 mg/dL.',
    dosageGuideMr: '• **मुख्य औषध:** **Glycomet 500 SR** (Metformin 500mg SR).\n• **डोस:** डॉक्टरांच्या सांगण्यानुसार दिवसातून १ किंवा २ वेळा जेवणासोबत किंवा जेवणानंतर लगेच.\n• **जेवणासोबत का:** यामुळे पोटात मळमळ किंवा त्रास होत नाही.\n• **साखरेचे प्रमाण:** उपाशीपोटी (Fasting) ८० ते १२० mg/dL, जेवणानंतर १६० mg/dL च्या आत असावी.',
    homeCareEn: '• Avoid white sugar, jaggery, sweets, cold drinks, white bread, and potatoes.\n• Eat whole grains (bajra, jowar roti), leafy greens, fenugreek (methi), and jamun.\n• Never walk barefoot on rough farm soil to prevent diabetic foot ulcers.\n• Exercise for 30-45 minutes daily.',
    homeCareMr: '• साखर, गूळ, मिठाई, बटाटा आणि बेकरीचे पदार्थ टाळा.\n• ज्वारी, बाजरीची भाकरी, पालेभाज्या, मेथी दाणे खा.\n• पायाला छोटीशीही जखम होऊ देऊ नका, शेतात अनवाणी चालू नका.\n• दररोज न चुकता चाला.',
    redFlagsEn: '🚨 Shivering, cold sweating, confusion, trembling (Low sugar / Hypoglycemia: Immediately eat 2 spoons of sugar or candy!), or non-healing foot wound.',
    redFlagsMr: '🚨 थरथर कापणे, थंड घाम येणे, चक्कर (साखर खूप कमी होणे: ताबडतोब २ चमचे साखर किंवा गोड खा!), किंवा पायाची न भरणारी जखम.',
    matchedMeds: ['Glycomet 500 SR']
  },
  {
    id: 'uti_kidney_stones',
    keywords: ['uti', 'urinary infection', 'urine burn', 'kidney stone', 'burning urine', 'लघवीची जळजळ', 'मूतखडा', 'किडनी स्टोन', 'लघवीला त्रास'],
    nameEn: 'Urinary Tract Infection (UTI) & Kidney Stones',
    nameMr: 'लघवीची जळजळ (UTI) आणि मूतखडा (Kidney Stone)',
    explanationEn: '• **UTI:** Bacterial entry into bladder/urethra causing intense burning during urination, frequent urge, and cloudy urine.\n• **Kidney Stones:** Mineral deposits (calcium oxalate) that form in kidneys and cause agonizing flank pain radiating down to the groin as they pass.',
    explanationMr: '• **लघवीतील इन्फेक्शन (UTI):** लघवी करताना तीव्र जळजळ, वारंवार लघवीला जावे वाटणे आणि ओटीपोटात दुखणे.\n• **मूतखडा (Kidney Stone):** लघवीतील क्षार जमा होऊन खडा तयार होतो. तो सरकताना पाठीच्या बाजूने पोटात व जांघेकडे असह्य कळा येतात.',
    dosageGuideEn: '• **For Burning Urination:** Urine Alkalizer Syrup (Citralka / Disodium Hydrogen Citrate) - 2 teaspoons in a full glass of water 3 times a day.\n• **Antibiotic for UTI:** Norfloxacin 400mg or Cefixime 200mg twice daily for 5 days strictly on doctor prescription.\n• **For Kidney Stone Spasm Pain:** Drotaverine 80mg or Drotin-M tablet.\n• **Stone Expulsion:** Ayurvedic Cystone / Neeri tablets (2 tablets twice daily) + abundant water intake.',
    dosageGuideMr: '• **लघवीतील जळजळीवर:** लघवी अल्कलाइन करणारे सिरप (उदा. Citralka) - २ चमचे एका ग्लास पाण्यात दिवसातून ३ वेळा.\n• **इन्फेक्शनवर अँटिबायोटिक:** डॉक्टरांच्या सल्ल्याने Norflox 400 किंवा Cefixime गोळ्या ५ दिवस.\n• **मूतखड्याच्या असह्य कळांवर:** Drotaverine (Drotin-M) गोळी.\n• **खडा पडून जाण्यासाठी:** Neeri किंवा Cystone गोळ्या आणि दिवसाला ४ लिटर पाणी.',
    homeCareEn: '• Drink 3 to 4 liters of clean water daily.\n• Drink barley water (jau ka paani), coconut water, and buttermilk.\n• Maintain strict genital hygiene.',
    homeCareMr: '• दिवसाला किमान ३ ते ४ लिटर स्वच्छ पाणी प्या.\n• नारळ पाणी, जवसाचे पाणी, ताक भरपूर प्या.\n• लघवी जास्त वेळ रोखून धरू नका.',
    redFlagsEn: '🚨 Blood in urine, high fever with shaking chills, or total inability to pass urine -> IMMEDIATE EMERGENCY.',
    redFlagsMr: '🚨 लघवीतून रक्त येणे, थंडी वाजून ताप येणे, किंवा लघवी पूर्णपणे बंद होणे -> तातडीने हॉस्पिटलमध्ये जा.',
    matchedMeds: ['Electral ORS Powder (WHO Formula)']
  },
  {
    id: 'skin_fungal_infection',
    keywords: ['fungal', 'ringworm', 'itching', 'scabies', 'rash', 'eczema', 'खाज', 'गजकर्ण', 'नायटा', 'दाद', 'खाज येणे'],
    nameEn: 'Fungal Infections (Ringworm/Jock Itch) & Skin Allergies',
    nameMr: 'गजकर्ण, नायटा, खाज आणि त्वचेचे बुरशीजन्य संसर्ग',
    explanationEn: 'Dermatophyte fungal microbes thrive in warm, moist body creases (groin, armpits, toes), causing red circular itchy rings with raised edges.',
    explanationMr: 'उष्ण व दमट हवामानामुळे किंवा घामामुळे त्वचेवर बुरशीची (Fungus) वाढ होते. जांघेत, काखेत किंवा शरीरावर गोलाकार लाल रंगाची खाज सुटणारी चकती तयार होते.',
    dosageGuideEn: '• **Topical Antifungal Cream:** Clotrimazole 1% or Terbinafine 1% cream.\n• **Application:** Apply a thin layer to clean, dry skin twice daily for 2 to 3 weeks.\n• **Rule:** Continue applying cream for at least 1 week AFTER the rash visibly disappears to prevent recurrence.\n• **For Allergic Itching:** Cetirizine 10mg (1 tablet at bedtime).\n• **For Severe Infection:** Itraconazole 100mg/200mg capsules strictly under doctor prescription.',
    dosageGuideMr: '• **लावायचा मलम:** Clotrimazole किंवा Terbinafine मलम.\n• **कसा लावावा:** जागा स्वच्छ व कोरडी करून दिवसातून २ वेळा २ ते ३ आठवडे लावावा.\n• **महत्त्वाचा नियम:** खाज बंद झाल्यानंतरही आणखी १ आठवडा मलम लावणे चालू ठेवावे जेणेकरून बुरशी मुळापासून नष्ट होईल.\n• **खाज थांबवण्यासाठी:** **Cetzine 10mg** गोळी रात्री झोपताना.\n• **गंभीर संसर्गावर:** डॉक्टरांच्या सल्ल्याने Itraconazole कॅप्सूल.',
    homeCareEn: '• Keep skin folds completely dry. Use antifungal dusting powder (Candid/Clocip).\n• Do not share towels, soaps, bedsheets, or clothes with family members.\n• Wash clothes in hot water and sun-dry thoroughly.',
    homeCareMr: '• अंग नेहमी कोरडे ठेवा. अँटीफंगल पावडरचा वापर करा.\n• टॉवेल, कपडे किंवा साबण घरातील इतरांसोबत शेअर करू नका.\n• कपडे गरम पाण्यात धुऊन कडक उन्हात वाळवा.',
    redFlagsEn: '🚨 Pus oozing, severe swelling, or spreading skin infection over whole body.',
    redFlagsMr: '🚨 जखमेतून पू येणे, खूप सूज येणे किंवा अंगावर इन्फेक्शन झपाट्याने पसरत असल्यास डॉक्टरांना दाखवा.',
    matchedMeds: ['Cetzine 10mg Tablets', 'Betadine 5% Antiseptic Ointment']
  },
  {
    id: 'mouth_ulcers',
    keywords: ['mouth ulcer', 'canker sore', 'tongue blister', 'mouth burn', 'तोंड येणे', 'जिभेवर फोड', 'तोंडातील अल्सर'],
    nameEn: 'Mouth Ulcers & Canker Sores',
    nameMr: 'तोंड येणे, जिभेवर फोड व तोंडातील जळजळ',
    explanationEn: 'Painful small mucosal erosions inside lips, cheeks, or tongue caused by Vitamin B12/Iron deficiency, stomach heat, sharp tooth irritation, or stress.',
    explanationMr: 'व्हिटॅमिन बी-कॉम्प्लेक्स किंवा लोहाच्या कमतरतेमुळे, पोटातील उष्णतेमुळे किंवा दाताने जीभ चावली गेल्यामुळे तोंडाच्या आत नाजूक त्वचेवर पांढरे फोड येतात.',
    dosageGuideEn: '• **Primary Vitamin Therapy:** **Becosules Z Capsules** - 1 capsule daily after food for 7 to 10 days.\n• **Instant Anesthetic Gel:** Choline Salicylate + Lignocaine gel (Zytee / Mucopain / Dologel) - Apply a small dab directly to the ulcer 3-4 times a day 10 minutes before meals for pain-free eating.\n• **Mouthwash:** Chlorhexidine mouthwash rinse twice daily.',
    dosageGuideMr: '• **मुख्य जीवनसत्त्व औषध:** **Becosules Z Capsules** - दररोज १ गोळी जेवणानंतर ७ ते १० दिवस घ्या.\n• **वेदना कमी करण्यासाठी मलम:** Zytee किंवा Dologel मलम जेवणाच्या १० मिनिटे आधी बोटाने फोडावर लावा, जेणेकरून जेवताना तिखट लागणार नाही.\n• **गुळण्या:** माउथवॉशने किंवा कोमट पाण्यात मीठ टाकून गुळण्या करा.',
    homeCareEn: '• Eat cooling foods: curd, buttermilk, coconut water, bananas.\n• Avoid raw chillies, very hot tea, smoking, gutkha, and paan masala.\n• Drink plenty of water to clear stomach toxins.',
    homeCareMr: '• थंड पदार्थ खा: ताक, दही, नारळ पाणी, तूप.\n• अति तिखट, गरम चहा, गुटखा आणि तंबाखू पूर्ण बंद करा.\n• भरपूर पाणी प्या.',
    redFlagsEn: '🚨 An ulcer that does not heal after 3 weeks, painless hard lump, or bleeding (requires biopsy screening to rule out oral cancer).',
    redFlagsMr: '🚨 ३ आठवड्यांपेक्षा जास्त काळ न भरणारा पांढरा डाग किंवा फोड (कॅन्सर तपासणीसाठी तातडीने डॉक्टरांकडे जा).',
    matchedMeds: ['Becosules Z Multivitamin Capsules']
  }
];

// ---------------------------------------------------------------------------
// 3. COMPREHENSIVE PAIN KNOWLEDGE BASE
// ---------------------------------------------------------------------------
export const PAIN_KNOWLEDGE_BASE = [
  {
    id: 'headache_migraine',
    keywords: ['headache', 'migraine', 'head pain', 'forehead pain', 'tension headache', 'डोकेदुखी', 'डोकं दुखणे', 'डोकं', 'डोके', 'डोक', 'अर्धशिशी', 'मायग्रेन', 'कपाळ'],
    nameEn: 'Headaches (Tension, Sinus & Migraine)',
    nameMr: 'डोकेदुखी, अर्धशिशी (Migraine) आणि सायनस डोकेदुखी',
    explanationEn: '• **Tension Headache:** Band-like dull ache around forehead from stress, lack of sleep, or eye strain.\n• **Migraine:** Severe throbbing, pulsing pain usually on one side of head, aggravated by bright light, sound, or smell, often accompanied by nausea.\n• **Sinus Headache:** Deep pain and pressure in forehead, cheekbones, and nose bridge, worse when bending forward.',
    explanationMr: '• **सामान्य डोकेदुखी:** ताणतणाव, अपुरी झोप किंवा डोळ्यांवरील ताणामुळे संपूर्ण कपाळ दुखणे.\n• **अर्धशिशी (Migraine):** डोक्याच्या एका बाजूला तीव्र ठसठसणे, सोबत मळमळ होणे आणि तीव्र प्रकाश किंवा आवाजाचा त्रास होणे.\n• **सायनस डोकेदुखी:** सर्दीमुळे कपाळ आणि गालांच्या हाडांमध्ये जडपणा व वेदना.',
    remedyGuideEn: '• **For Tension & General Headache:** **Paracetamol 650mg (Dolo 650)** - 1 tablet after food.\n• **For Migraine:** Naproxen + Domperidone or Sumatriptan under doctor prescription. Rest in a dark, quiet room with cold compress on forehead.\n• **For Sinus Headache:** Inhale steam twice daily + Cetirizine 10mg at night + Paracetamol for pain.\n• **Topical Relief:** Apply gentle menthol balm or Volini gel on temples and back of neck.',
    remedyGuideMr: '• **सामान्य डोकेदुखीवर:** **Dolo 650 (Paracetamol)** - जेवणानंतर १ गोळी.\n• **मायग्रेनवर:** अंधाऱ्या, शांत खोलीत विश्रांती घ्या, कपाळावर थंड पाण्याची पट्टी ठेवा.\n• **सायनस डोकेदुखीवर:** गरम पाण्याची वाफ घ्या आणि **Cetzine 10mg** रात्री घ्या.\n• **मलम:** कपाळावर किंवा मानेवर हलका बाम लावा.',
    precautionsEn: 'Avoid skipping meals, dehydration, and excessive mobile/TV screen exposure. Limit coffee/tea dependence.',
    precautionsMr: 'वेळेवर जेवण करा, भरपूर पाणी प्या आणि मोबाईलचा अती वापर टाळा.',
    redFlagsEn: '🚨 Sudden, explosive "worst headache of your life" (thunderclap), headache with stiff neck and high fever, or loss of balance (Emergency Brain/Stroke alert -> CALL 108).',
    redFlagsMr: '🚨 अचानक विजेसारखी असह्य डोकेदुखी, मानेतील तीव्र कडकपणा आणि ताप, किंवा तोल जाणे -> तातडीने हॉस्पिटलमध्ये जा.',
    matchedMeds: ['Paracetamol 650mg (Dolo 650)', 'Cetzine 10mg Tablets']
  },
  {
    id: 'knee_joint_back_pain',
    keywords: ['knee pain', 'joint pain', 'back pain', 'backache', 'arthritis', 'sciatica', 'spine', 'lumbago', 'गुडघेदुखी', 'पाठदुखी', 'कंबरदुखी', 'सांधेदुखी', 'मणक्याचा त्रास', 'गुडघा', 'गुडघे', 'कंबर', 'सांधे', 'पाठ'],
    nameEn: 'Joint Pain, Knee Osteoarthritis & Back Pain',
    nameMr: 'गुडघेदुखी, कंबरदुखी, सांधेदुखी आणि मणक्याचे विकार',
    explanationEn: 'Joint pain occurs from cartilage wear-and-tear (osteoarthritis), calcium/Vitamin D deficiency, or farm labor strain. Back pain is commonly due to lumbar muscle spasms, disc compression, or posture.',
    explanationMr: 'गुडघ्यातील व सांध्यातील वंगण (Cartilage) कमी झाल्यामुळे, कॅल्शियमच्या कमतरतेमुळे किंवा शेतात वाकून जड काम केल्याने मणक्यावर व सांध्यांवर ताण येऊन तीव्र वेदना होतात.',
    remedyGuideEn: '• **Immediate Topical Relief:** **Volini Pain Relief Gel** - Apply a thin layer 3 to 4 times daily over knees/back. Gently spread without hard massaging.\n• **Bone & Joint Strength:** **Shelcal 500** (Calcium + Vitamin D3) - 1 tablet daily after food.\n• **For Severe Pain Spasm:** Paracetamol 650mg after food. If taking NSAIDs (Aceclofenac/Diclofenac), ALWAYS take with food + Pan-D to protect stomach lining.\n• **Warm Therapy:** Apply a warm water heating pad for 15 minutes twice daily.',
    remedyGuideMr: '• **बाहेरून लावण्यासाठी:** **Volini Pain Relief Gel** - दुखऱ्या जागेवर दिवसातून ३-४ वेळा हलक्या हाताने लावा.\n• **हाडांच्या मजबुतीसाठी:** **Shelcal 500** (कॅल्शियम + व्हिटॅमिन डी३) - दररोज जेवणानंतर १ गोळी.\n• **तीव्र वेदना असल्यास:** Dolo 650 किंवा डॉक्टरांच्या सल्ल्याने पेनकिलर (नेहमी जेवणानंतर व ॲसिडिटीची गोळी सोबत घ्यावी).\n• **शेक देणे:** गरम पाण्याच्या पिशवीने दुखऱ्या भागाला सकाळ-संध्याकाळ शेक द्या.',
    precautionsEn: 'Avoid sitting cross-legged on the floor if you have severe knee arthritis. Do not lift heavy loads during acute back pain. Wear cushioned footwear.',
    precautionsMr: 'जमिनीवर मांडी घालून बसणे टाळा. जड वजन उचलू नका. चालताना मऊ चप्पल वापरा.',
    redFlagsEn: '🚨 Severe back pain accompanied by loss of bladder/bowel control, numbness in both legs, or high fever with joint swelling (Septic Arthritis).',
    redFlagsMr: '🚨 पाठीच्या दुखण्यासोबत लघवीवर ताबा न राहणे, दोन्ही पाय सुन्न पडणे किंवा सांधा लाल होऊन प्रचंड ताप भरणे.',
    matchedMeds: ['Volini Pain Relief Gel (50g)', 'Shelcal 500 Calcium & Vitamin D3', 'Paracetamol 650mg (Dolo 650)']
  },
  {
    id: 'stomach_pain_cramps',
    keywords: ['stomach pain', 'abdominal pain', 'belly pain', 'cramps', 'stomach ache', 'पोटदुखी', 'पोटात मुरडा', 'पोटात दुखणे', 'पोट दुख', 'मळमळ', 'पोट', 'मुरडा'],
    nameEn: 'Stomach Pain, Abdominal Cramps & Spasms',
    nameMr: 'पोटदुखी, पोटात मुरडा येणे आणि पोटात दुखणे',
    explanationEn: 'Abdominal pain has varied causes: gas spasms, indigestion, intestinal infection, food poisoning, menstrual cramps, kidney stones, or appendix inflammation.',
    explanationMr: 'पोटदुखीची वेगवेगळी कारणे असू शकतात: गॅसमुळे पोट फुगणे, अपचन, अन्नाची विषबाधा, मासिक पाळीतील पोटदुखी, मूतखडा किंवा अपेंडिक्सची सूज.',
    remedyGuideEn: '• **For Gas & Burning Acid Pain:** **Pan-D Capsules** on empty stomach + Antacid syrup.\n• **For Painful Spasms & Cramps:** Drotaverine 80mg (Drotin) or Mefenamic Acid + Drotaverine (Meftal-Spas) - 1 tablet after food.\n• **For Menstrual (Period) Cramps:** Meftal-Spas tablet + warm heating bag on lower abdomen.\n• **For Loose Motion with Cramps:** Electral ORS hydration + light diet.',
    remedyGuideMr: '• **गॅस व जळजळीमुळे पोट दुखत असल्यास:** **Pan-D** उपाशीपोटी आणि जेलुसिल सिरप.\n• **पोटात मुरडा किंवा पिळवटून दुखत असल्यास:** Meftal-Spas किंवा Drotin गोळी जेवणानंतर.\n• **मासिक पाळीतील पोटदुखीवर:** Meftal-Spas गोळी आणि पोटावर गरम पाण्याचा शेक.\n• **जुलाब व पोटदुखी:** ओआरएसचे पाणी प्या.',
    precautionsEn: 'Do not take heavy painkillers like Brufen or Diclofenac for unexplained stomach pain as they can cause stomach bleeding.',
    precautionsMr: 'पोटदुखीवर साधे ब्रुफेन किंवा डिक्लोफेनाकसारखे पेनकिलर घेऊ नका, यामुळे पोटात अल्सर होऊ शकतो.',
    redFlagsEn: '🚨 Severe sharp pain starting around belly button and shifting to LOWER RIGHT abdomen with vomiting and fever (CLASSIC APPENDICITIS -> DO NOT DELAY, GO TO EMERGENCY SURGERY IMMEDIATELY!).',
    redFlagsMr: '🚨 पोटाच्या उजव्या बाजूला खाली असह्य कळ येणे, उलटी व ताप (हे अपेंडिक्सचे लक्षण असू शकते -> घरगुती उपाय न करता त्वरित सर्जन किंवा हॉस्पिटलमध्ये जा!).',
    matchedMeds: ['Pan-D Capsules', 'Electral ORS Powder (WHO Formula)']
  },
  {
    id: 'toothache_gum_pain',
    keywords: ['toothache', 'tooth pain', 'gum pain', 'teeth', 'दातदुखी', 'हिरड्या', 'दात किडणे', 'दाढ दुखणे', 'दात', 'दाढ'],
    nameEn: 'Toothache, Gum Swelling & Dental Infection',
    nameMr: 'दातदुखी, दाढ दुखणे आणि हिरड्यांची सूज',
    explanationEn: 'Usually caused by dental caries (cavities) exposing the sensitive nerve pulp, bacterial abscess, or wisdom tooth eruption.',
    explanationMr: 'दात किंवा दाढ किडल्यामुळे, दातात अन्नाचे कण अडकून जंतूसंसर्ग झाल्यामुळे किंवा अक्कलदाढ येताना हिरडी सुजून असह्य दातदुखी होते.',
    remedyGuideEn: '• **Immediate Pain Relief:** **Paracetamol 650mg** or Ketorolac DT (dispersible tablet in water) after food.\n• **Natural Remedy:** Apply pure Clove Oil (लवंग तेल) on a tiny cotton ball directly on the hollow cavity.\n• **Mouth Rinse:** Swish warm salt water for 1 minute 4 times a day.\n• **For Bacterial Abscess (Pus):** Augmentin 625 Duo or Amoxicillin strictly under dentist prescription.',
    remedyGuideMr: '• **तात्काळ वेदनाशामक:** **Dolo 650** गोळी जेवणानंतर घ्या.\n• **घरगुती उपाय:** कापसाच्या बोळ्यावर लवंगाचे तेल लावून दुखणाऱ्या दाढेवर धरा.\n• **गुळण्या:** कोमट पाण्यात मीठ टाकून दिवसातून ३-४ वेळा गुळण्या करा.\n• **हिरडीत पू असल्यास:** डॉक्टरांच्या सल्ल्याने अँटिबायोटिक (Augmentin 625) कोर्स करा.',
    precautionsEn: 'Do NOT place aspirin tablet directly on the gum as it causes chemical tissue burn. Visit a dentist for cavity filling or root canal.',
    precautionsMr: 'हिरडीवर गोळी चोळू नका. दातातील कीड काढून घेण्यासाठी दंतवैद्यांना (Dentist) दाखवा.',
    redFlagsEn: '🚨 Facial swelling extending to eye or neck, difficulty swallowing or breathing.',
    redFlagsMr: '🚨 चेहऱ्यावर किंवा मानेवर मोठी सूज येणे किंवा गिळण्यास त्रास होणे.',
    matchedMeds: ['Paracetamol 650mg (Dolo 650)', 'Augmentin 625 Duo']
  },
  {
    id: 'chest_pain_triage',
    keywords: ['chest pain', 'heart', 'angina', 'छातीत दुखणे', 'हार्ट', 'छातीवर ताण', 'छाती दुख'],
    nameEn: 'Chest Pain Emergency Triage (Heart vs. Gas vs. Muscular)',
    nameMr: 'छातीत दुखणे - आपत्कालीन वर्गीकरण (हार्ट, गॅस की स्नायूदुखी?)',
    explanationEn: '• 🚨 **HEART ATTACK (Emergency):** Heavy crushing pressure, squeezing, or fullness in center of chest, radiating to left shoulder, arm, neck, or jaw, accompanied by cold sweat, shortness of breath, or dizziness.\n• **ACIDITY / GAS:** Burning sensation behind breastbone (heartburn), sour taste, worsens after heavy food or lying down, relieved by antacids.\n• **MUSCULOSKELETAL:** Sharp pain tender to touch with fingertips, worsens when taking a deep breath or twisting torso.',
    explanationMr: '• 🚨 **हार्ट अटॅक (धोकादायक):** छातीच्या मधोमध जड वजन ठेवल्यासारखा असह्य दाब, डाव्या हाताकडे किंवा जबड्याकडे कळ जाणे, सोबत थंड घाम व दम लागणे.\n• **पित्त / गॅस:** छातीत जळजळ होणे, करपट ढेकर येणे, जेवणानंतर वाढणे.\n• **स्नायूदुखी:** छातीवर बोटाने दाबल्यास किंवा शरीर वळवल्यास दुखणे.',
    remedyGuideEn: '🚨 If you suspect Cardiac Chest Pain:\n1. Call **108** or Guru Medical Hotline **8237729148** immediately.\n2. Chew an Aspirin 300mg (Ecosprin) or Sorbitrate 5mg under the tongue if prescribed.\n3. Keep the patient sitting upright and calm; DO NOT let them walk.\n\n• If clearly proven to be acidity: Take Pan-D capsule + Antacid syrup.',
    remedyGuideMr: '🚨 हृदयाशी संबंधित दुखण्याची शंका असल्यास:\n१. तात्काळ **१०८** किंवा गुरु मेडिकल **8237729148** वर फोन करा.\n२. रुग्णाला शांत बसवून ठेवा, चालायला लावू नका.\n३. डॉक्टरांच्या सल्ल्याने Ecosprin गोळी चघळावी.\n\n• केवळ साधी ॲसिडिटी असल्यास Pan-D व जेलुसिल सिरप घ्या.',
    precautionsEn: 'NEVER ignore chest pain. Always treat unexplained chest pain as a medical emergency until proven otherwise by an ECG.',
    precautionsMr: 'छातीतील दुखण्याकडे कधीही दुर्लक्ष करू नका. त्वरित ईसीजी (ECG) करून खात्री करा.',
    redFlagsEn: '🚨 CRITICAL RED FLAG: Any chest pressure with cold sweating and breathlessness requires IMMEDIATE AMBULANCE INTERVENTION.',
    redFlagsMr: '🚨 छातीवर तीव्र दाब व थंड घाम आल्यास एक सेकंदही वाया न घालवता हॉस्पिटलमध्ये जा.',
    matchedMeds: ['Pan-D Capsules']
  }
];
